# Generated by Django 2.2.16 on 2023-10-03 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robots', '0002_auto_20231003_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='robot',
            name='serial',
            field=models.CharField(default=2, max_length=5),
            preserve_default=False,
        ),
    ]
