# Generated by Django 4.2.5 on 2023-10-05 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robots', '0003_robot_serial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='robot',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='robotmodel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
